language: python

dist: bionic

python:
  - "3.6"

before_install:
  - sudo apt-get --yes --force-yes update -qq


after_success:
  - pip install -r docs/requirements.txt 
  - git checkout -b gh-pages origin/gh-pages
  - rm -rf *
  - git checkout master docs
  - git reset HEAD
  - cd docs
  - make html
  - cd ..
  - mv -f docs/_build/html/* .
  - touch .nojekyll
  - rm -rf docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master

warnings_are_errors: true
