kind: Deployment
apiVersion: apps/v1
metadata:
        name: jupyterlab-audio-gpu-0-5-1-hostpath-pv
        namespace: kubeflow
spec:
        replicas: 1 # This is the number of containers that are going to be deployed.
        selector:
                matchLabels:
                        app: jupyterlab-audio-gpu-0-5-1-hostpath-pv-app
        template:
                metadata:
                        labels:
                                app: jupyterlab-audio-gpu-0-5-1-hostpath-pv-app
                spec:
                        containers: 
                        - name: jupyterlab-audio-gpu-0-5-1-hostpath-pv
                          imagePullPolicy: Always
                          image: sipecam/audio-dgpi-kale-gpu:0.5.1
                          ports:
                                  - containerPort: 8888
                          env:
                                  - name: mount_point
                                    value: /shared_volume
                                  - name: LC_ALL
                                    value: C.UTF-8
                                  - name: LANG
                                    value: C.UTF-8
                          resources:
                                  requests:
                                          cpu: ".5" # This value depends of type of AWS instance chosen
                                          memory: 15Gi # This value depends of type of AWS instance chosen
                                  limits:
                                          cpu: ".5" # This value depends of type of AWS instance chosen
                                          memory: 15Gi # This value depends of type of AWS instance chosen
                                          nvidia.com/gpu: 1
                          volumeMounts:
                                  - name: hostpath-pv
                                    mountPath: "/shared_volume"
                        volumes:
                        - name: hostpath-pv
                          persistentVolumeClaim:
                                  claimName: hostpath-pvc    
