kind: Service
apiVersion: v1
metadata:
        name: kale-service-kubeflow-0-4-0-1-14-0-tf-cpu
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 9999
                  targetPort: 9999
                  protocol: TCP
                  nodePort: 30002 #select port of your preference
        selector:
                app: kale-jupyterlab-kubeflow-0-4-0-1-14-0-tf-cpu-app


