kind: Service
apiVersion: v1
metadata:
        name: kale-service-jupyterlab
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 9999
                  targetPort: 9999
                  protocol: TCP
                  nodePort: 30001 #select port of your preference
        selector:
                app: kale-jupyterlab-app


