kind: Service
apiVersion: v1
metadata:
        name: kale-service-kubeflow_1.14.0_tfx
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 9999
                  targetPort: 9999
                  protocol: TCP
                  nodePort: 30002 #select port of your preference
        selector:
                app: kale-jupyterlab-kubeflow_1.14.0_tfx-app


