kind: Service
apiVersion: v1
metadata:
        name: kale-service-kubeflow_0.4.0_1.14.0_tf
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 9999
                  targetPort: 9999
                  protocol: TCP
                  nodePort: 30001 #select port of your preference
        selector:
                app: kale-jupyterlab-kubeflow_0.4.0_1.14.0_tf-app


