kind: Service
apiVersion: v1
metadata:
        name: tfx-service-kubeflow-1-14-0-tfx
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 9999
                  targetPort: 9999
                  protocol: TCP
                  nodePort: 30002 #select port of your preference
        selector:
                app: tfx-jupyterlab-kubeflow-1-14-0-tfx-app


