kind: Deployment
apiVersion: extensions/v1beta1
metadata:
        name: tfx-jupyterlab-kubeflow-1-14-0-tfx
        namespace: kubeflow
spec:
        replicas: 1 # This is the number of containers that are going to be deployed.
        template:
                metadata:
                        labels:
                                app: tfx-jupyterlab-kubeflow-1-14-0-tfx-app
                        annotations:
                                iam.amazonaws.com/role: "arn:aws:iam::<micuenta>:role/<mirol>"
                spec:
                        containers: 
                        - name: tfx-jupyterlab-kubeflow-1-14-0-tfx-app
                          imagePullPolicy: Always
                          image: sipecam/audio-tfx:1.14.0_tfx
                          ports:
                                  - containerPort: 9999
                          env:
                                  - name: mount_point
                                    value: /shared_volume
                                  - name: LC_ALL
                                    value: C.UTF-8
                                  - name: LANG
                                    value: C.UTF-8
                          resources:
                                  requests:
                                          cpu: "1" # This value depends of type of AWS instance chosen
                                          memory: .5Gi # This value depends of type of AWS instance chosen
                                  limits:
                                          cpu: "1" # This value depends of type of AWS instance chosen
                                          memory: .5Gi # This value depends of type of AWS instance chosen
                                          nvidia.com/gpu: 1
                          volumeMounts:
                                  - name: efs-pvc
                                    mountPath: "/shared_volume"
                        volumes:
                        - name: efs-pvc
                          persistentVolumeClaim:
                                  claimName: efs
                     
