kind: Service
apiVersion: v1
metadata:
        name: loadbalancer-mad-mex-0-5-0-0-1-0
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 8888
                  targetPort: 8888
                  protocol: TCP
                  nodePort: 30001 #select port of your preference
        selector:
                app: jupyterlab-mad-mex-0-5-0-0-1-0-app