apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: kubeflow
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
