apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: kubeflow
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem #or Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /shared_volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <ip of node example: ip-10-0-2-108>
