kind: Service
apiVersion: v1
metadata:
        name: loadbalancer-audio-tensorflow-yuntu-dask-gpu-0-6-1-hostpath-pv
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 8888
                  targetPort: 8888
                  protocol: TCP
                  nodePort: 30002 #select port of your preference
        selector:
                app: jupyterlab-audio-tensorflow-yuntu-dask-gpu-0-6-1-hostpath-pv-app
