apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storageclass
  namespace: kubeflow
reclaimPolicy: Retain
allowVolumeExpansion: true
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
