kind: Service
apiVersion: v1
metadata:
        name: kale-service-kubeflow-0-1-0-1-7-0-0-5-0-hostpath-pv
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 8888
                  targetPort: 8888
                  protocol: TCP
                  nodePort: 30001 #select port of your preference
        selector:
                app: kale-jupyterlab-kubeflow-0-1-0-1-7-0-0-5-0-hostpath-pv-app